#exec setxkbmap dvorak &
setxkbmap -layout us -variant dvp &
#exec feh --bg-center Pictures/42960-shark-at-the-bottom-of-the-sea-1920x1200-animal-wallpaper.jpg &
#exec feh --bg-scale /home/torben/Pictures/tv-noise-20108.jpg &
#exec sudo bluetoothctl connect 00:58:50:4D:30:FE &
xfce4-terminal &
#exec chrome &
#exec chromium-browser &
firefox &
#exec opera &
clipit -n &
bash /home/torben/bin/keyboard-delay &
bash /home/torben/development/dwm_sss/dwm-sss &
#exec polybar --reload example &
bash ~/bin/slack &
xmodmap /home/torben/.Xmodmap &
ssh -MNf hetzner2 &
